import * as esbuild from 'esbuild';

await esbuild.build({
  entryPoints: ['src/cli/index.ts'],
  bundle: true,
  platform: 'node',
  target: 'node18',
  format: 'esm',
  outdir: 'dist/cli',
  external: [
    'react',
    'react-dom',
    'react-reconciler',
    'yoga-layout-prebuilt',
    'chalk',
    'commander',
    'events',
    'http',
    'https',
    'url',
    'path',
    'fs',
    'os',
    'crypto',
    'stream',
    'util',
    'assert',
    'buffer',
    'zlib',
    'net',
    'tls',
    'querystring',
    'dns'
  ],
  sourcemap: true,
  minify: false,
  mainFields: ['module', 'main'],
});

await esbuild.build({
  entryPoints: ['src/index.ts'],
  bundle: true,
  platform: 'node',
  target: 'node18',
  format: 'esm',
  outdir: 'dist',
  external: [
    'react',
    'react-dom',
    'react-reconciler',
    'yoga-layout-prebuilt',
    'chalk',
    'commander',
    'events',
    'http',
    'https',
    'url',
    'path',
    'fs',
    'os',
    'crypto',
    'stream',
    'util',
    'assert',
    'buffer',
    'zlib',
    'net',
    'tls',
    'querystring',
    'dns'
  ],
  sourcemap: true,
  minify: false,
  mainFields: ['module', 'main'],
});

console.log('Build complete');